name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "DATABASE_NAME=conversations.db" >> .env
          echo "FLASK_ENV=development" >> .env
          echo "DEBUG=True" >> .env

      - name: Initialize database
        run: |
          source .venv/bin/activate
          python initialize_db.py

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=5 --disable-warnings

