name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Configurar repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Exportar variables de entorno desde .env
      - name: Load environment variables
        run: |
          set -o allexport
          source .env || true
          set +o allexport

      # Ejecutar pruebas
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=5 --disable-warnings

